---
title: "Syllabus"
---

# Introduction

## Land Acknowledgement

UBC's Point Grey Campus is located on the traditional, ancestral, and unceded territory of the [xʷməθkʷəy̓əm (Musqueam)](https://www.musqueam.bc.ca/) people.
The land it is situated on has always been a place of learning for the Musqueam people, who for millennia have passed on their culture, history, and traditions from one generation to the next on this site.

## TL;DR

## Instructor information

Stephan graduated in Biology at the Ruprecht Karl University in Heidelberg, Germany, and obtained his Ph.D. in Evolutionary Biology at the University of New Brunswick in Fredericton.

Stephan has been working at UBC since 2018.
He was a Research Associate in Dr. Sally Otto's lab and then a Postdoctoral Teaching and Learning Fellow under the supervision of Dr. Steven Hallam in the Microbiology and Immunology Department, coordinating the Experiential Data science for Undergraduate Cross-disciplinary Education (EDUCE) program.
He designed and delivered data science-focused modules across multiple MICB courses, conducted and analyzed surveys, and maintained open education resources.

In 2022, Stephan joined Skylight (Science Centre of Learning and Teaching) as the Science Education Specialist in the Computer Science Department, where he supports instructors with the migration to a new online assessment tool offering students the opportunity to practice with randomized questions for mastery learning and more flexibility when scheduling exams in a new computer-based testing facility.
He focuses on the impact of learning technologies on student learning, well-being and inclusivity and how their implementation and course design should inform each other.

Hi 👋,

My name is Stephan Koenig, I use [He, Him pronouns](https://equity.ubc.ca/resources/gender-diversity/pronouns/), and I am a son, brother, husband, and father.
I am an evolutionary biologist by training and a self-taught data scientist, a jack of all trades and master of none, a teacher and a student.
I previously worked as a PostDoc Teaching and Learning Fellow in the Microbiology and Immunology Department at the University of British Columbia (UBC), coordinating the [EDUCE initiative](https://educe-ubc.github.io).
As a [Skylight](https://skylight.science.ubc.ca) Science Education Specialist in the Computer Science Department at UBC, I think about how modern computational tools can enhance teaching and learning.
I often fantasize about unshackling files from directories and love the colour orange, pour-over coffee & Markdown.

## Course description and learning objectives

## Textbook / lecture material

## iClicker

## Course requirements

## Course content and schedule

## Copyright

Open education resources and you!

## Grading and exam policies

## Accessibility

## Academic misconduct
